# Generated by Django 6.1 on 2026-08-23 18:59

import userapp.constants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('matric_number', models.CharField(db_index=True, max_length=20)),
                ('department_code', models.CharField(max_length=10)),
                ('level', models.PositiveIntegerField()),
                ('session_start', models.PositiveIntegerField(default=userapp.constants.session_start_year)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('authorization_url', models.URLField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('gateway_response', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('BIO', 'Biology'), ('CHM', 'Chemistry'), ('CSC', 'Computer Science'), ('MTH', 'Mathematics'), ('PHY', 'Physics'), ('STA', 'Statistics')], max_length=10)),
                ('level', models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(default='Departmental Dues', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', '-level'],
                'constraints': [models.UniqueConstraint(fields=('department', 'level'), name='unique_fee_per_dept_level')],
            },
        ),
    ]
