# Generated by Django 6.1 on 2026-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.PositiveIntegerField(help_text='First calendar year of the active session, e.g. 2026 for 2026/27.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session configuration',
                'verbose_name_plural': 'Session configuration',
            },
        ),
    ]
